ALTER TABLE users
    ADD COLUMN phone VARCHAR(30),
    ADD COLUMN class_name VARCHAR(100),
    ADD COLUMN subject VARCHAR(150);

ALTER TABLE quizzes
    ADD COLUMN subject VARCHAR(150),
    ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE results
    ADD COLUMN correct_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN total_questions INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN time_spent_seconds INTEGER NOT NULL DEFAULT 0;
